---
title: "Deepfaking"
subtitle: "Analyses"
author: "Sean Hughes"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r include=FALSE}
knitr::opts_chunk$set(message=FALSE,
                      warning=FALSE)
```

.libPaths()


# Dependencies & functions

```{r}

# dependencies -----
library(tidyverse)
library(ggthemes)
library(knitr)
library(kableExtra)
library(broom)
library(effsize)
library(BayesFactor)
library(metafor)
library(ez)
library(schoRsch)
library(nnet)
library(epitools)

options(knitr.kable.NA = "/")

# Ensures that the processed data folder exists
dir.create("models")
dir.create("results")

# functions -----
# round p value using apa format
apa_p_value <- function(p){
  p_formatted <- ifelse(p >= 0.0001, paste("=", round(p, 4)),
                        ifelse(p < 0.0001, "< .0001", NA))
  p_formatted <- gsub(pattern = "0.", replacement = ".", x = p_formatted, fixed = TRUE)
  p_formatted
}

# calculate cohens d and return its output in tidy format - a helper function for analysis_workflow
tidy_cohens_d <- function(data){
  require(effsize)

  fit <- effsize::cohen.d(DV ~ IV, data = data)

  results <- tibble(cohens_d = fit$estimate,
                    cohens_d_ci_lower = fit$conf.int["lower"],
                    cohens_d_ci_upper = fit$conf.int["upper"])

  return(results)
}

# calculate cohens d and return its output in tidy format - a helper function for analysis_workflow
tidy_ttest_bf <- function(data){
  require(BayesFactor)

  fit <- data %>%
    ttestBF(formula = DV ~ IV, data = .)

  results <- data.frame(bf10 = extractBF(fit)$bf)
  return(results)
}


# full analysis workflow
# NB workflow returns mean_reference and mean_comparison, where reference is the first factor level and comparison is the next highest level.
analysis_workflow <- function(data){

  # frequentist t test
  results_t_test <- data %>%
    group_by(experiment, DV_type) %>%
    do(broom::tidy(t.test(DV ~ IV, data = .))) %>%
    ungroup() %>%
    rename(t = statistic,
           df = parameter,
           p = p.value,
           mean_reference = estimate1,
           mean_comaprison = estimate2)

  # cohens d
  results_cohens_d <- data %>%
    group_by(experiment, DV_type) %>%
    do(tidy_cohens_d(data = .)) %>%
    ungroup()

  # BF t test
  results_bf_t_test <- data %>%
    group_by(experiment, DV_type) %>%
    do(tidy_ttest_bf(data = .)) %>%
    ungroup()

  # combine
  results <-
    full_join(results_t_test,
              results_cohens_d,
              by = c("experiment", "DV_type")) %>%
    full_join(results_bf_t_test,
              by = c("experiment", "DV_type")) %>%
    select(experiment, DV_type,
           mean_reference, mean_comaprison,
           t, df, p, cohens_d, cohens_d_ci_lower, cohens_d_ci_upper, bf10) %>%
    mutate(reportable_result = paste0("Positive video M = ", round(mean_reference, 2), ", Negative video M = ", round(mean_comaprison, 2), ", t(", round(df, 2), ") = ", round(t, 2), ", p ", apa_p_value(p), ", d = ", round(cohens_d, 2), ", 95% CI [", round(cohens_d_ci_lower, 2), ", ", round(cohens_d_ci_upper, 2), "], BF10 = ", round(bf10, 1)))

  return(results)
}

OR_to_d <- function(OR){
  log(OR)*(sqrt(3)/pi)
}

```

# Data and exclusions

```{r}

# full data
data_processed <-
      read_csv("C:/Users/Sean/Desktop/git/Deepfaking/Experiment 2 (b)/2. Data/processed/data_processed.csv") %>%
  # set factor levels for t test comparisons
  mutate(experiment_condition = fct_relevel(experiment_condition,
                                            "Positive Video",
                                            "Negative Video")) %>%
  # create exclusion variable for IAT data
  mutate(exclude_iat = ifelse(complete_iat_data == "complete" & passed_iat_performance == TRUE,
                          FALSE, TRUE),
         # if exclude variable is missing, then exclude
         exclude_iat = ifelse(is.na(exclude_iat), TRUE, exclude_iat)) %>%
  # create exclusion variable for missing exploratory question data 
  mutate(exclude_exploratory = ifelse(is.na(memory_of_video_content), TRUE,
                                      ifelse(is.na(diagnosticity_question), TRUE,
                                             ifelse(is.na(demand), TRUE, 
                                                    ifelse(is.na(reactance), TRUE, 
                                                           ifelse(is.na(hypothesis_awareness), TRUE,
                                                                  ifelse(is.na(influence_awareness), TRUE, FALSE))))))) %>%
  #create compound exclusion criteria
  mutate(exclude = exclude_iat + exclude_exploratory)
  
  # remove missing data
data_processed_after_exclusions <- data_processed %>%
  filter(exclude == 0) 


```

# Demographics

```{r}

data_processed %>%
  summarise(n = n(),
            age_mean = mean(age, na.rm = TRUE),
            age_sd = sd(age, na.rm = TRUE),
            excluded_n = sum(exclude > 0),
            excluded_percent = (excluded_n / n) *100) %>%
  mutate_if(is.numeric, round, digits = 1) %>%
  kable(align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

data_processed %>%
  count(experiment, gender) %>%
  spread(gender, n) %>%
  kable(knitr.kable.NA = "/", align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)



write_csv(data_processed_after_exclusions, "results/data_processed_after_exclusions.csv")

```

# Analyses by study

## Was there a basic evaluative learning effect?

### IAT & self_reports

- by DV
- Differences between experimental condition (positive vs. negative video)

```{r}

results_basic_effect_iat_selfreports <- data_processed_after_exclusions %>%
  rename(IV = experiment_condition) %>%
  gather(DV_type, DV, c(self_reported_rating, IAT_D2_score)) %>%
  select(experiment, DV_type, DV, IV) %>%
  drop_na() %>%
  analysis_workflow(data = .)

write_csv(results_basic_effect_iat_selfreports, "results/results_basic_effect_iat_selfreports.csv")

results_basic_effect_iat_selfreports %>%
  select(experiment, DV_type, reportable_result) %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

```
