---
title: "Combined hand scored data files"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes 
    toc_float: yes
---

```{r include=FALSE}
knitr::opts_chunk$set(message=FALSE,
                      warning=FALSE)
```

```{r}

library(tidyverse)
library(readxl)

data_hs_4 <- read_excel("data_for_hand_scoring_exp_4.xlsx") %>%
  select(subject, 
         recognised_manipulation = recognised_audio_manipulation,
         deepfake_check_recoded)

data_hs_5 <- read_excel("data_for_hand_scoring_exp_5.xlsx") %>%
  select(subject, 
         recognised_manipulation = recognised_video_manipulation, 
         deepfake_check_recoded = deepfake_video_check_recoded, 
         deepfake_concept_check_recoded)

data_hs_6 <- read_excel("data_for_hand_scoring_exp_6.xlsx") %>%
  select(subject, 
         recognised_manipulation = recognised_audio_manipulation, 
         deepfake_check_recoded = deepfake_audio_check_recoded, 
         deepfake_concept_check_recoded)

data_hand_scored_combined <- 
  bind_rows(data_hs_4,
            data_hs_5,
            data_hs_6) %>%
  filter(!is.na(subject)) %>%
  mutate(deepfake_detected = case_when(deepfake_check_recoded == "Yes" ~ TRUE,
                                       deepfake_check_recoded == "No" ~ FALSE),
         manipulation_detected = case_when(recognised_manipulation == "Yes" ~ TRUE,
                                           recognised_manipulation == "No" ~ FALSE),
         deepfake_concept_check = case_when(deepfake_concept_check_recoded == "Yes" ~ TRUE,
                                            deepfake_concept_check_recoded == "No" ~ FALSE)) %>%
  select(subject, 
         deepfake_detected,
         manipulation_detected,
         deepfake_concept_check)

# data_hand_scored_combined %>%
#   count(deepfake_detected,
#         manipulation_detected,
#         deepfake_concept_check) %>%
#   arrange(desc(n))

write_csv(data_hand_scored_combined, "data_hand_scored_rater_1.csv")

```
