---
title: "Data postprocessing"
subtitle: "Integrate hand-scored data into final dataset"
author: "Sean Hughes & Ian Hussey"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes 
    toc_float: yes
---

Note that open ended text responses are dropped by this script, to produce a data file that contains only the data needed for analyses. Text responses can still be found in "2.2_data_participant_level.csv".

```{r include=FALSE}
knitr::opts_chunk$set(message=FALSE,
                      warning=FALSE)
```

# Dependencies

```{r}

library(tidyverse)

```

# Get data and join

```{r}

# read in processed data
# because read_csv uses just the first 1000 rows to guess data types, mean_intentions incorrectly parses as logical. so, col types have to be manually specified for all columns.
data_participant_level <- read.csv("processed/2.2_data_participant_level.csv")

# hand scored data
data_hand_scored_rater_1 <- read_csv("processed/3_data_hand_scored_rater_1.csv") %>%
  dplyr::select(subject, 
                deepfake_detected_rater_1, 
                deepfake_concept_check_rater_1)

data_hand_scored_rater_2 <- read_csv("processed/3_data_hand_scored_rater_2.csv") %>%
  dplyr::select(subject, 
                deepfake_detected_rater_2, 
                deepfake_concept_check_rater_2)

# join
data_participant_level_with_hand_scoring <- data_participant_level %>%
  full_join(data_hand_scored_rater_1, by = "subject") %>%
  full_join(data_hand_scored_rater_2, by = "subject") %>%
  
  # create single variables between raters. 
  # emphasizes specificity by requiring both raters to score as TRUE, therefore providing a more severe test of learning even in those who were aware.
  mutate(deepfake_detected = 
           case_when(deepfake_detected_rater_1 == TRUE & deepfake_detected_rater_2 == TRUE ~ TRUE,
                     is.na(deepfake_detected_rater_1) & is.na(deepfake_detected_rater_2) ~ NA,
                     TRUE ~ FALSE),
         deepfake_concept_check = 
           case_when(deepfake_concept_check_rater_1 == TRUE & deepfake_concept_check_rater_2 == TRUE ~ TRUE,
                     is.na(deepfake_concept_check_rater_1) & is.na(deepfake_concept_check_rater_2) ~ NA,
                     TRUE ~ FALSE)) %>%
  
  # drop open ended text responses now that they've been coded for analysis
  select(subject,
         experiment,
         intervention_medium,
         source_valence,
         experiment_condition,
         exclude_subject,
         exclude_implausible_intervention_linger,
         intervention_linger_minutes,
         age,
         gender,
         IAT_D2,
         mean_self_reported_evaluation,
         mean_intentions,
         deepfake_detected,
         
         # item level data
         ratings_bad_good,
         ratings_dislike_like,
         ratings_negative_positive,
         behavioral_intentions_share,
         behavioral_intentions_subscribe,
         behavioral_intentions_recommend,
         ## NB IAT item level data is written to disk as a separate file
         
         # exploratory measures
         diagnosticity,
         demand,
         reactance,
         hypothesis_awareness,
         influence_awareness,
         ## individual difference measures - sum scores
         aot_actively_openminded_thinking_sum,
         bcti_belief_in_conspiracy_sum,
         crt_analytic_thinking_sum,
         ocq_overclaiming_sum,
         ras_relgious_affliation_sum,
         rei_rational_sum,
         rei_experiential_sum,
         me_fake_news_awareness_sum,
         me_real_news_awareness_sum,
         me_fake_news_accuracy_sum,
         me_real_news_accuracy_sum,
         me_fake_news_sharing_sum,
         me_real_news_sharing_sum,
         ## individual difference measures - POMP scores
         aot_actively_openminded_thinking_pomp,
         bcti_belief_in_conspiracy_pomp,
         crt_analytic_thinking_pomp,
         ocq_overclaiming_pomp,
         ras_relgious_affliation_pomp,
         rei_rational_pomp,
         rei_experiential_pomp,
         me_fake_news_awareness_pomp,
         me_real_news_awareness_pomp,
         me_fake_news_accuracy_pomp,
         me_real_news_accuracy_pomp,
         me_fake_news_sharing_pomp,
         me_real_news_sharing_pomp,
         
         # recoded DVs - mentioned in preregistrations but not used in my (more appropriate) reworked analyses. 
         IAT_D2_recoded_for_source_valence,
         mean_self_reported_evaluation_recoded_for_source_valence,
         mean_intentions_recoded_for_source_valence,
         
         # individual raters
         deepfake_concept_check,
         deepfake_detected_rater_1,
         deepfake_detected_rater_2,
         deepfake_concept_check_rater_1,
         deepfake_concept_check_rater_2,
         
         # additional demographics
         gender_self_describe,
         ethnicity,
         ethnicity_self_describe,
         location,
         education,
         employment,
         education_recoded,
         income,
         income_recoded,
         political_ideology_identity,
         political_ideology_social_issues,
         political_ideology_economic_issues,
         religious_affiliation_general,
         religious_affiliation_general_recoded,
         passed_iat_performance,
         
         # component exclusion variables
         complete_iat,
         complete_selfreport,
         complete_intentions,
         
         # methods variables
         task_order,
         iat_block_order)

```

# Write to disk

```{r}

write_csv(data_participant_level_with_hand_scoring, "processed/4_data_participant_level_with_hand_scoring.csv")

```



