---
title: "Codebook for processed data"
subtitle: "Add data labels, metadata, codebook, distributions, and convert to other file types"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r include=FALSE}
knitr::opts_chunk$set(message=FALSE,
                      warning=FALSE)
```

# Codebook

```{r}

# Following codebook package's [vignette](https://cran.r-project.org/web/packages/codebook/vignettes/codebook_tutorial.html)

# Dependencies

library(tidyverse)
library(knitr)
library(kableExtra)
library(codebook)
library(labelled)
library(rio)

options(knitr.kable.NA = "/")


# Add labels ----

# read data
codebook_data <- read.csv("processed/4_data_participant_level_with_hand_scoring.csv")

# read data dictionary
dict <- read.csv("processed/5_data_dictionary.csv", row.names=NULL, sep = ";")

# add dictionary as labels
var_label(codebook_data) <- dict %>% 
  select(variable, label) %>% 
  dict_to_list()


# Add meta data ----

metadata(codebook_data)$name <- "Evaluative learning via deepfaked media"
metadata(codebook_data)$description <- "Across multiple experiments, we demonstrated that 'deepfakes' can establish automatic biases, self-reported evaluations, and behavioural intentions."
#metadata(codebook_data)$identifier <- "https://dx.doi.org/XXXXXXX"

metadata(codebook_data)$creator <- "Sean Hughes"
metadata(codebook_data)$citation <- "Hughes, S., Fried, O., Ferguson, M. J., Yao, D., Hughes, C., Hughes, R., & Hussey, I. (2020). Using Deepfakes to Hack the Human Mind."
metadata(codebook_data)$url <- "https://github.com/Sean-Hughes/DF-Impression-Formation--Video-and-Audio-"

# other meta data:  see https://schema.org/Dataset
metadata(codebook_data)$datePublished <- "2020"
metadata(codebook_data)$spatialCoverage <- "Online" 


# Create codebook ----

codebook(codebook_data)

```

# Write alternative file types to disk

Original csv file is used for analyses (as it is simplest), but other file types that integrate the labels are likely to be more useful for reuse. 

I include an R .rds file (which includes data labels and data types), SPSS .sav and Stata .dta files. 

```{r}

write_rds(codebook_data, "processed/4_data_participant_level_with_hand_scoring.rds") 
rio::export(codebook_data, "processed/4_data_participant_level_with_hand_scoring.sav") # SPSS file
rio::export(codebook_data, "processed/4_data_participant_level_with_hand_scoring.dta") # Stata file

```

# Session Info

```{r}

sessionInfo()

```



